app/urls.py
from django.urls import path
from app.views import (
    HomeView,
    TaskCompleteUndoView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    TagListView,
    TagCreateView,
    TagUpdateView,
    TagDeleteView
)

app_name = "app"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path(
        "complete_undo_task/<int:pk>/",
        TaskCompleteUndoView.as_view(),
        name="task_complete_undo"
    ),
    # Task
    path("task/create/", TaskCreateView.as_view(), name="task-create"),
    path(
        "task/<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"
    ),
    path(
        "task/<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"
    ),
    # Tag
    path("tags/", TagListView.as_view(), name="tags"),
    path("tag/create/", TagCreateView.as_view(), name="tag-create"),
    path("tag/<int:pk>/update/", TagUpdateView.as_view(), name="tag-update"),
    path("tag/<int:pk>/delete/", TagDeleteView.as_view(), name="tag-delete"),

]

todo_list/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("app.urls", namespace="app"))
]

if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self) -> str:
        return f"{self.name}"


class Task(models.Model):
    content = models.TextField()
    datetime_created = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(null=True, blank=True)
    is_done = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag, related_name="tasks")

    class Meta:
        ordering = ["-datetime_created", "is_done"]

    def __str__(self) -> str:
        return f"{self.content}"

app/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Field, Submit
from app.models import Task, Tag


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ["content", "deadline", "tags"]

    def __init__(self, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = "post"
        self.helper.form_class = "base-form"

        self.fields["deadline"].widget = forms.DateTimeInput(
            format="%Y-%m-%d %H:%M",
            attrs={"type": "datetime-local"}
        )

        self.helper.layout = Layout(
            Field("content", css_class="form-control"),
            Field("deadline", css_class="form-control"),
            Field("tags", css_class="form-control"),
            Submit("submit", "Submit"))


class TagForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = ["name"]

    def __init__(self, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = "post"
        self.helper.form_class = "base-form"

        self.helper.layout = Layout(
            Field("name", css_class="form-control"),
            Submit("submit", "Submit"))

app/views.py
from django.shortcuts import redirect
from django.http import HttpRequest, HttpResponseRedirect
from django.views import generic
from django.urls import reverse_lazy
from django.db.models import QuerySet
from app.forms import TaskForm, TagForm
from app.models import Task, Tag


# Task
class HomeView(generic.ListView):
    model = Task
    paginate_by = 3

    def get_queryset(self) -> QuerySet[Task]:
        return Task.objects.all().order_by("is_done", "-datetime_created")


class TaskCompleteUndoView(generic.View):
    def get(self, request: HttpRequest, pk: int) -> HttpResponseRedirect:
        return redirect(reverse_lazy("app:home"))

    def post(self, request: HttpRequest, pk: int) -> HttpResponseRedirect:
        task = Task.objects.get(pk=pk)
        action = request.POST.get("action")
        if action == "complete":
            task.is_done = True
        elif action == "undo":
            task.is_done = False
        task.save()
        return redirect(reverse_lazy("app:home"))


class TaskBaseView:
    model = Task
    success_url = reverse_lazy("app:home")


class TaskCreateView(TaskBaseView, generic.CreateView):
    form_class = TaskForm


class TaskUpdateView(TaskBaseView, generic.UpdateView):
    form_class = TaskForm


class TaskDeleteView(TaskBaseView, generic.DeleteView):
    pass


# Tag
class TagBaseView:
    model = Tag
    success_url = reverse_lazy("app:tags")


class TagListView(generic.ListView):
    model = Tag
    paginate_by = 3

    def get_queryset(self) -> QuerySet[Tag]:
        return Tag.objects.all().order_by("-id")


class TagCreateView(TagBaseView, generic.CreateView):
    form_class = TagForm


class TagUpdateView(TagBaseView, generic.UpdateView):
    form_class = TagForm


class TagDeleteView(TagBaseView, generic.DeleteView):
    pass

templates/app/tag_confirm_delete.html
{% extends 'base.html' %}

{% block title %}
Delete Tag
{% endblock title %}

{% block header %}
Delete tag: {{ tag.name }}
{% endblock header %}

{% block content %}
<div class="container">
  <h2>Are you sure you want to delete tag "{{ tag.name }}"?</h2>

  <form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Delete</button>
    <a href="{% url 'app:tags' %}" class="btn btn-secondary">Cancel</a>
  </form>
</div>
{% endblock content %}

templates/app/tag_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}
{% if request.resolver_match.url_name == 'tag-create' %}
Create Tag
{% elif request.resolver_match.url_name == 'tag-update' %}
Update Tag
{% endif %}
{% endblock title %}

{% block header %}
{% if request.resolver_match.url_name == 'tag-create' %}
Create a new tag
{% elif request.resolver_match.url_name == 'tag-update' %}
Update tag
{% endif %}
{% endblock header %}

{% block content %}
<div class="container">
  <div class="col-sm-12 col-md-8 col-lg-6">
    {% crispy form %}
  </div>
</div>
{% endblock content %}

templates/app/tag_list.html
{% extends 'base.html' %}

{% block title %}
TODO Tags
{% endblock title %}

{% block header %}
TODO Tags
{% endblock header %}

{% block content %}
<div class="container">
  <div class=" col-sm-12 col-md-12 col-lg-10">
    <div class="row mb-3">
      <div class="col text-right">
        <a href="{% url 'app:tag-create' %}" class="btn btn-primary">Add Tag +</a>
      </div>
    </div>
    <table class="table table-bordered">
      <thead>
      <tr>
        <th scope="col" class="col-md-10">Name</th>
        <th scope="col" class="col-md-2">Actions</th>
      </tr>
      </thead>
      <tbody>
      {% for tag in tag_list %}
      <tr class="">
        <td><strong>{{ tag.name }}</strong></td>
        <td>
          <div class="d-flex">
            <a href="{% url 'app:tag-update' tag.pk %}" class="btn btn-warning btn-sm mr-2">Update</a>
            <a href="{% url 'app:tag-delete' tag.pk %}" class="btn btn-danger btn-sm mr-2">Delete</a>
          </div>
        </td>
      </tr>
      {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock content %}

templates/app/task_confirm_delete.html
{% extends 'base.html' %}

{% block title %}
Delete Task
{% endblock title %}

{% block header %}
Delete task: {{ task.content }}
{% endblock header %}

{% block content %}
<div class="container">
  <h2>Are you sure you want to delete task "{{ task.content }}"?</h2>

  <form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Delete</button>
    <a href="{% url 'app:home' %}" class="btn btn-secondary">Cancel</a>
  </form>
</div>
{% endblock content %}

templates/app/task_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}
{% if request.resolver_match.url_name == 'task-create' %}
Create Task
{% elif request.resolver_match.url_name == 'task-update' %}
Update Task
{% endif %}
{% endblock title %}

{% block header %}
{% if request.resolver_match.url_name == 'task-create' %}
Create a new task
{% elif request.resolver_match.url_name == 'task-update' %}
Update task
{% endif %}
{% endblock header %}

{% block content %}
<div class="container">
  <div class="col-sm-12 col-md-8 col-lg-6">
    {% crispy form %}
  </div>
</div>
{% endblock content %}

templates/app/task_list.html
{% extends 'base.html' %}

{% block title %}
TODO list
{% endblock title %}

{% block header %}
TODO List
{% endblock header %}

{% block content %}
<div class="container">
  <div class="row mb-3">
    <div class="col text-right">
      <a href="{% url 'app:task-create' %}" class="btn btn-primary">Add Task +</a>
    </div>
  </div>
  <table class="table table-bordered">
    <thead>
    <tr>
      <th scope="col">Content</th>
      <th scope="col">Created</th>
      <th scope="col">Deadline</th>
      <th scope="col">Tags</th>
      <th scope="col">Actions</th>
    </tr>
    </thead>
    <tbody>
    {% for task in task_list %}
    <tr class="{% if task.is_done %}table-success{% else %}table-danger{% endif %}">
      <td><strong>{{ task.content }}</strong></td>
      <td>{{ task.datetime_created }}</td>
      <td>{% if task.deadline %}<span class="deadline">{{ task.deadline }}</span>
        {% else %}No deadline{% endif %}
      </td>
      <td>
        {% for tag in task.tags.all %}
        <span class="badge badge-info">{{ tag.name }}</span>
        {% endfor %}
      </td>
      <td>
        <div class="d-flex">
          <a href="{% url 'app:task-update' task.pk %}" class="btn btn-warning btn-sm mr-2">Update</a>
          <a href="{% url 'app:task-delete' task.pk %}" class="btn btn-danger btn-sm mr-2">Delete</a>
          <form method="post" action="{% url 'app:task_complete_undo' task.id %}">
            {% csrf_token %}
            <input type="hidden" name="action" value="{% if task.is_done %}undo{% else %}complete{% endif %}">
            <button type="submit" class="btn btn-sm {% if task.is_done %}btn-secondary{% else %}btn-success{% endif %}">
              {% if task.is_done %}Undo{% else %}Complete{% endif %}
            </button>
          </form>
        </div>
      </td>
    </tr>
    {% endfor %}
    </tbody>
  </table>
</div>
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}{% endblock title %}</title>
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>

<div class="container-fluid" style="display: flex;">
  <div class="sidebar col-sm-3 col-md-3 col-lg-2">
    {% include 'includes/sidebar.html' %}
  </div>
  <div class="content col-sm-9 col-md-9 col-lg-10">
    <h1>{% block header %}{% endblock header %}</h1>
    {% block content %}
    {% endblock content %}
    {% if paginator %}
    {% include 'includes/pagination.html' %}
    {% endif %}
  </div>
</div>

{% block JavaScript %}
{% endblock JavaScript %}
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.2/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

templates/includes/pagination.html
<div class="pagination">
    <span class="step-links">
      {% if page_obj.has_previous %}
        <a href="?page=1">&laquo; first</a>
        <a href="?page={{ page_obj.previous_page_number }}">previous</a>
      {% endif %}

      <span class="current">
        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
      </span>

      {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">next</a>
        <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
      {% endif %}
    </span>
</div>

templates/includes/sidebar.html
<nav>
  <h3>To-do App</h3>
  <ul>
    <li><a class="{% if request.path == '/' %} active {% endif %}" href="{% url 'app:home' %}">Home</a></li>
    <li><a class="{% if request.path == '/tags/' %} active {% endif %}" href="{% url 'app:tags' %}">Tags</a></li>
  </ul>
</nav>